### ISSUE TITLE
Rejected for receipt validation

### ISSUE THREAD

**Issue by rsodre** [rmaddy/VerifyStoreReceiptiOS#9]
Hello,

My app is being rejected with the following "bug", when they try to restore a purchase:

```
We found that your app has incorrectly implemented receipt validation, so it does not properly distinguish between the review (sandbox) environment and the production environment. This is resulting in a validation query to the production servers instead of a sandbox receipt check, and is preventing us from being able to review your app.

To address this issue, please revise your binary to include the necessary logic required to differentiate between the review and production environments.
```

I never validate receipts with any server, I just ask for a refresh with SKReceiptRefreshRequest, which automatically routes to the current environment.

```
SKReceiptRefreshRequest *request = [[SKReceiptRefreshRequest alloc] init];
```

I'm using VerifyStoreReceiptiOS's obtainInAppPurchases(), it does not query any server, but they insist I'm querying the production server while in review environment.

And everything works fine for me!

To me, it sounds like a flaw in the review environment, I shouldn't have to include ifs to see if it's production or review, everything is supposed to direct to the current logged environment.

Roger

**Comment by tomasikp** [comment]
The app you submit for review should be signed for distribution i.e. everything should be ready for production.  Why would it validate against a sandbox environment unless it were signed for dev/int and hitting a dev/int server.  I have never had an issue like the one you are describing.

**Comment by rsodre** [comment]
Could it be that simple, a signing mistake? Makes sense, but I think Apple would reject the binary right away if it was uploaded with a development certificate.
I'll upload again taking extra caution and let's see what's happen...

**Comment by rsodre** [comment]
Ok, this is embarrassing (for Apple).
Tech support answered me this...

"when the app starts, it checks for the presence of the unified receipt - when there is none, it calls the SKReceiptRefreshRequest method, which causes the presentation of the StoreKit dialog for the App Reviewer to enter their user credentials so that a unified receipt will be obtained. Waht you are not aware of, is that this method fails to return a unified receipt in the App Review environment. There is a complicated reason for this which I cannot discuss. This happen even if you provide a valid test user account. The SKReceiptRefreshRequest works properly everywhere - EXCEPT in the App Review environment. In the App Review environment, the presentation of the StoreKit dialog is problematic and no unified receipt is provided to the application."

It means, we cannot use SKReceiptRefreshRequest at the moment. Will we ever be able to use it again? Who knows?

So the solution they gave me is... "The supported means for restoring non-consumable purchases is with the use of the restoreCompletedTransaction method."

Let's go again...

**Comment by fadookie** [comment]
WTF Apple?!? This response equates to: "We are rejecting your app because we can't test the code you wrote following our documentation exactly. Clearly, this means our review environment is broken and beyond useless, however we are passing the burden of this on to you instead of fixing it."

Roger, could you file a radar bug on this at https://bugreport.apple.com/?
My friends who have worked at Apple said that bugs filed through radar usually make their way to engineers and often actually get addressed.

**Comment by rsodre** [comment]
Good idea, I'll file a bug report.
In the end I got an answer from tech support confirming they cannot test SKReceiptRefreshRequest in review environment. It's a known problem, and he cannot talk about it. Then i convinced the review tram to approve my app based on that, and they approved it. But now I need to make an update, and probably it will start again...

**Comment by an0** [comment]
I'm experiencing the exactly same rejection. But in my case, I don't have any workaround to resort to because I'm validating receipt for paid app not IAP.

The only way to do local receipt validation is to check existing receipt first and refresh using SKReceiptRefreshRequest if no valid one is found. Apple gives us no way to detect whether the app is running in the review (sandbox) environment or the production environment so the same validation code will run when they are reviewing our apps. So the App Store account sign-in alert will be prompted. The sad thing is that the reviewer will immediately reject your app at the first sight of this sign-in alert and insist that I implemented receipt validation incorrectly.

I'm trying to explain to them that I'm strictly following their documentation and implemented local receipt validation correctly and the sign-in alert is shown by SKReceiptRefreshRequest — the exact and only framework Apple tells us to use to do local receipt validation — and I have to use it if I want to do local receipt validation. It seems local receipt validation is rarely used and the reviewers are not familiar with it.

We've already did several rounds of communication and I'm still explaining. In the last mail, I attached this thread URL as a reference. Hope they will look here and see what problem it is exactly. Especially, @rsodre's case let me see some light. Good luck, all of us!

**Comment by fadookie** [comment]
@rsodre Once you've filed the bug, can you post a link/issue # here so we can keep track of its status? Thanks!

**Comment by rsodre** [comment]
Bug filed #17575116 : App Store review team unable to test SKReceiptRefreshRequest

I have to resubmit the app, and as now I'm supporting iOS 6, I'll use:

```
[[SKPaymentQueue defaultQueue] restoreCompletedTransactions];
```

In the end it's the same thing, just treat SKPaymentTransactionStateRestored like an SKPaymentTransactionStatePurchased

**Comment by escoz** [comment]
Hi @an0 any luck on getting the app approved? I"m in the same boat, Apple just rejected my binary because of this same issue, and I also use the app version from the receipt, so can't change it.

**Comment by an0** [comment]
@escoz I use timing to avoid validation during review.

**Comment by escoz** [comment]
@an0 do you mind expanding on what you mean? Did you just put a timer to avoid doing receipt validation on the first 2 weeks of the app, or something similar? I'm not sure why Apple is complaining about the two environments, and asking to change the URLs used for testing, when I'm doing the validation inside the app. Thanks!

**Comment by an0** [comment]
@escoz Yes, use a timer.

**Comment by mickeyl** [comment]
Any idea whether this insane review situation has changed in the past two years? And if not... if you're using a timer, do you then use "normal" transaction processing for IAPs until the timer fires?
